version: 2

before:
  hooks:
    - go clean -cache

project_name: goecs

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./
    binary: goecs

  - id: linux-arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    goos:
      - linux
    goarch:
      - arm64
    main: ./
    binary: goecs

  - id: linux-386
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    goos:
      - linux
    goarch:
      - 386
    main: ./
    binary: goecs

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: "goecs_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - New translations

upx:
  - enabled: true
    brute: true
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
